CREATE DATABASE IF NOT EXISTS JOGOSOLIMPICOS;

-- DROP DATABASE JOGOSOLIMPICOS;

USE JOGOSOLIMPICOS;

CREATE TABLE IF NOT EXISTS CONTACTO (
idContacto INT NOT NULL AUTO_INCREMENT,
email VARCHAR(45) NOT NULL,
PRIMARY KEY (idContacto)
);
-- DROP TABLE CONTACTO

CREATE TABLE IF NOT EXISTS MORADA (
idMorada INT NOT NULL AUTO_INCREMENT,
rua VARCHAR(45) NOT NULL,
nPorta INT NOT NULL,
localidade VARCHAR(45) NOT NULL,
codPostal VARCHAR(45) NOT NULL,
pais VARCHAR(45) NOT NULL,
detalhes TEXT NULL,
PRIMARY KEY (idMorada)
);
-- DROP TABLE MORADA

CREATE TABLE IF NOT EXISTS JOGOSOLIMPICOS (
edicao INT NOT NULL AUTO_INCREMENT,
dataInicio DATE NOT NULL,
dataFim DATE NOT NULL,
idContacto INT NOT NULL,
idMorada INT NOT NULL,
PRIMARY KEY (edicao),
FOREIGN KEY (idContacto) REFERENCES CONTACTO(idContacto),
FOREIGN KEY (idMorada) REFERENCES MORADA(idMorada)
);
-- DROP TABLE JOGOSOLIMPICOS

-- describe ?

CREATE TABLE IF NOT EXISTS EQUIPA(
idEquipa INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
edicao INT NOT NULL,
PRIMARY KEY (idEquipa, edicao),
FOREIGN KEY (edicao) REFERENCES JOGOSOLIMPICOS(edicao)
);
-- DROP TABLE EQUIPA

CREATE TABLE IF NOT EXISTS ATLETA(
idAtleta INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
idade INT NOT NULL,
peso INT NOT NULL,
altura INT NOT NULL,
genero VARCHAR(45) NOT NULL,
idEquipa INT NOT NULL,
edicao INT NOT NULL,
idContacto INT NOT NULL,
PRIMARY KEY (idAtleta),
FOREIGN KEY (idEquipa) REFERENCES EQUIPA(idEquipa),
FOREIGN KEY (edicao) REFERENCES JOGOSOLIMPICOS(edicao),
FOREIGN KEY (idContacto) REFERENCES CONTACTO(idContacto)
);
-- DROP TABLE ATLETA

CREATE TABLE IF NOT EXISTS PODIO(
idPodio INT NOT NULL AUTO_INCREMENT,
descricao VARCHAR(45) NOT NULL,
idAtleta INT NOT NULL,
PRIMARY KEY (idPodio),
FOREIGN KEY (idAtleta) REFERENCES ATLETA(idAtleta)
);
-- DROP TABLE PODIO

CREATE TABLE IF NOT EXISTS PASSAPORTEBIOLOGICO(
idPassaporteBiologico INT NOT NULL AUTO_INCREMENT,
idAtleta INT NOT NULL,
PRIMARY KEY (idPassaporteBiologico),
FOREIGN KEY (idAtleta) REFERENCES ATLETA(idAtleta)
);
-- DROP TABLE PASSAPORTEBIOLOGICO

CREATE TABLE IF NOT EXISTS TESTEDOPING(
idTesteDoping INT NOT NULL AUTO_INCREMENT,
dataRealizado DATETIME NOT NULL,
tipo ENUM("Sangue", "Urina", "Tecnológico") NOT NULL,
resultado TINYINT NOT NULL,
observacoes TEXT NULL,
idPassaporteBiologico INT NOT NULL,
PRIMARY KEY (idTesteDoping),
FOREIGN KEY (idPassaporteBiologico) REFERENCES PASSAPORTEBIOLOGICO(idPassaporteBiologico)
);
-- DROP TABLE TESTEDOPING

CREATE TABLE IF NOT EXISTS MODALIDADE(
idModalidade INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
edicao INT NOT NULL,
PRIMARY KEY (idModalidade),
FOREIGN KEY (edicao) REFERENCES JOGOSOLIMPICOS(edicao)
);
-- DROP TABLE MODALIDADE

CREATE TABLE IF NOT EXISTS EVENTO(
idEvento INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
tipo ENUM("Singular", "Múltiplos") NOT NULL,
regulamento TEXT NOT NULL,
dataEvento DATETIME NOT NULL,
idModalidade INT NOT NULL,
PRIMARY KEY (idEvento),
FOREIGN KEY (idModalidade) REFERENCES MODALIDADE(idModalidade)
);
-- DROP TABLE EVENTO

CREATE TABLE IF NOT EXISTS RESULTADO(
idResultado INT NOT NULL AUTO_INCREMENT,
posicao TEXT NOT NULL,
detalhes TEXT,
idEvento INT NOT NULL,
idAtleta INT NOT NULL,
PRIMARY KEY (idResultado),
FOREIGN KEY (idEvento) REFERENCES EVENTO(idEvento),
FOREIGN KEY (idAtleta) REFERENCES ATLETA(idAtleta)
);
-- DROP TABLE RESULTADO

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
idFuncionario INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(45) NOT NULL,
dataNascimento DATE NOT NULL,
tipo ENUM("Voluntário", "Regulador", "Administrador") NOT NULL,
idContacto INT NOT NULL,
edicao INT NOT NULL,
PRIMARY KEY (idFuncionario, edicao),
FOREIGN KEY (idContacto) REFERENCES CONTACTO(idContacto),
FOREIGN KEY (edicao) REFERENCES JOGOSOLIMPICOS(edicao)
);
-- DROP TABLE FUNCIONARIO

CREATE TABLE IF NOT EXISTS EVENTO_HAS_ATLETA(
idEvento INT NOT NULL,
idAtleta INT NOT NULL,
PRIMARY KEY (idEvento, idAtleta), -- devia ser separado?
FOREIGN KEY (idEvento) REFERENCES EVENTO(idEvento),
FOREIGN KEY (idAtleta) REFERENCES ATLETA(idAtleta)
);
-- DROP TABLE EVENTO_HAS_ATLETA

CREATE TABLE IF NOT EXISTS EVENTO_HAS_FUNCIONARIO(
idEvento INT NOT NULL,
idFuncionario INT NOT NULL,
edicao INT NOT NULL,
PRIMARY KEY (idEvento, idFuncionario, edicao),
FOREIGN KEY (idEvento) REFERENCES EVENTO(idEvento),
FOREIGN KEY (edicao) REFERENCES JOGOSOLIMPICOS(edicao),
FOREIGN KEY (idFuncionario) REFERENCES FUNCIONARIO(idFuncionario)
);
-- DROP TABLE EVENTO_HAS_FUNCIONARIO

DELETE FROM `jogosolimpicos`.`jogosolimpicos`
WHERE <{where_expression}>;
